apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 10255
    protocol: TCP
  selector:
    app: flask-app
